### ISSUE TITLE
creative menu

### ISSUE THREAD

**Issue by JadeOfTheSky** [ApexModder/Registrator#1]
unsure if it's an issue specifically with this mod, but upon opening the creative mode menu with apex and fantasy dice, the game will crash.

A [crash report](https://gnomebot.dev/paste/945023738120896553) will be included, if that helps

.

**Comment by ApexModder** [comment]
Belive it or not this is actually an issue with ApexCore ([#1](https://github.com/ApexModder/ApexCore/issues/1))

working on a fix for it right now.

**Comment by ApexModder** [comment]
@JadeOfTheSky Issue fixed in ApexCore [1.16.5-1.1.28](https://www.curseforge.com/minecraft/mc-mods/apexcore/files/3655608) & [1.18.1-3.0.6](https://www.curseforge.com/minecraft/mc-mods/apexcore/files/3655614)
